version: "3.3"

services:
  revproxy0:
    image: nginx
    restart: always
    command: /bin/bash -c "envsubst '$$PROXY_PASS' < /nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx0.conf:/nginx.conf
    environment:
      - PROXY_PASS=http://revproxy1:81/
    ports:
      - "80:80"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
  revproxy1:
    image: nginx
    restart: always
    command: /bin/bash -c "envsubst '$$PROXY_PASS $$AUTH_REALM' < /nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx1.conf:/nginx.conf
      - ./htpasswd:/etc/nginx/conf.d/htpasswd
    environment:
      - PROXY_PASS=http://xxxxxxxxxxxxxxxx:8080/
      - AUTH_REALM=BasicAuth ReverseProxy
    ports:
      - "81:81"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
