version: "3.3"

services:
  revproxy:
    image: nginx
    restart: always
    command: /bin/bash -c "envsubst '$$PROXY_PASS' < /nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/nginx.conf
    environment:
      - PROXY_PASS=${PROXY_PASS}
    ports:
      - "${PORT}:80"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
